---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/,http://localhost:9011/eureka/,http://localhost:9012/eureka/
---
spring:
  profiles: subject
words: I,You,He,She,It
---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog
